package echo.music.iad1tya.settings

import kotlinx.coroutines.flow.Flow


// Auto-generated by migration script

var SettingsManager.isFirstRun: Boolean
    get() = getBoolean("isFirstRun", false)
    set(value) = setBoolean("isFirstRun", value)

fun SettingsManager.isFirstRunFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("isFirstRun", default)

var SettingsManager.dataSaverEnabled: Boolean
    get() = getBoolean("dataSaverEnabled", false)
    set(value) = setBoolean("dataSaverEnabled", value)

fun SettingsManager.dataSaverEnabledFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("dataSaverEnabled", default)

var SettingsManager.spotifySpDc: String
    get() = getString("spotify_sp_dc", "")
    set(value) = setString("spotify_sp_dc", value)

fun SettingsManager.spotifySpDcFlow(default: String = ""): Flow<String> = getStringFlow("spotify_sp_dc", default)

var SettingsManager.spotifySp: String
    get() = getString("spotify_sp_key", "")
    set(value) = setString("spotify_sp_key", value)

fun SettingsManager.spotifySpFlow(default: String = ""): Flow<String> = getStringFlow("spotify_sp_key", default)

var SettingsManager.spotifyAccountName: String
    get() = getString("spotify_account_name", "")
    set(value) = setString("spotify_account_name", value)

fun SettingsManager.spotifyAccountNameFlow(default: String = ""): Flow<String> = getStringFlow("spotify_account_name", default)

var SettingsManager.spotifyAccountAvatarUrl: String
    get() = getString("spotify_account_avatar_url", "")
    set(value) = setString("spotify_account_avatar_url", value)

fun SettingsManager.spotifyAccountAvatarUrlFlow(default: String = ""): Flow<String> = getStringFlow("spotify_account_avatar_url", default)

var SettingsManager.spotifyAccessToken: String
    get() = getString("spotify_access_token", "")
    set(value) = setString("spotify_access_token", value)

fun SettingsManager.spotifyAccessTokenFlow(default: String = ""): Flow<String> = getStringFlow("spotify_access_token", default)

var SettingsManager.spotifyAccessTokenExpiresAt: Long
    get() = getLong("spotify_access_token_expires_at", 0L)
    set(value) = setLong("spotify_access_token_expires_at", value)

fun SettingsManager.spotifyAccessTokenExpiresAtFlow(default: Long = 0L): Flow<Long> = getLongFlow("spotify_access_token_expires_at", default)

var SettingsManager.enableDynamicIcon: Boolean
    get() = getBoolean("enableDynamicIcon", false)
    set(value) = setBoolean("enableDynamicIcon", value)

fun SettingsManager.enableDynamicIconFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("enableDynamicIcon", default)

var SettingsManager.enableLegacyIcon: Boolean
    get() = getBoolean("enableLegacyIcon", false)
    set(value) = setBoolean("enableLegacyIcon", value)

fun SettingsManager.enableLegacyIconFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("enableLegacyIcon", default)

var SettingsManager.appIconType: String
    get() = getString("app_icon_type", "")
    set(value) = setString("app_icon_type", value)

fun SettingsManager.appIconTypeFlow(default: String = ""): Flow<String> = getStringFlow("app_icon_type", default)

var SettingsManager.enableHighRefreshRate: Boolean
    get() = getBoolean("enableHighRefreshRate", false)
    set(value) = setBoolean("enableHighRefreshRate", value)

fun SettingsManager.enableHighRefreshRateFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("enableHighRefreshRate", default)

var SettingsManager.enableHaptics: Boolean
    get() = getBoolean("enableHaptics", false)
    set(value) = setBoolean("enableHaptics", value)

fun SettingsManager.enableHapticsFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("enableHaptics", default)

var SettingsManager.dynamicTheme: Boolean
    get() = getBoolean("dynamicTheme", false)
    set(value) = setBoolean("dynamicTheme", value)

fun SettingsManager.dynamicThemeFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("dynamicTheme", default)

var SettingsManager.selectedThemeColor: Int
    get() = getInt("selectedThemeColor", 0)
    set(value) = setInt("selectedThemeColor", value)

fun SettingsManager.selectedThemeColorFlow(default: Int = 0): Flow<Int> = getIntFlow("selectedThemeColor", default)

var SettingsManager.darkMode: String
    get() = getString("darkMode", "")
    set(value) = setString("darkMode", value)

fun SettingsManager.darkModeFlow(default: String = ""): Flow<String> = getStringFlow("darkMode", default)

var SettingsManager.pureBlack: Boolean
    get() = getBoolean("pureBlack", false)
    set(value) = setBoolean("pureBlack", value)

fun SettingsManager.pureBlackFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("pureBlack", default)

var SettingsManager.pureBlackMiniPlayer: Boolean
    get() = getBoolean("pureBlackMiniPlayer", false)
    set(value) = setBoolean("pureBlackMiniPlayer", value)

fun SettingsManager.pureBlackMiniPlayerFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("pureBlackMiniPlayer", default)

var SettingsManager.miniPlayerOutline: Boolean
    get() = getBoolean("miniPlayerOutline", false)
    set(value) = setBoolean("miniPlayerOutline", value)

fun SettingsManager.miniPlayerOutlineFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("miniPlayerOutline", default)

var SettingsManager.densityScale: Float
    get() = getFloat("density_scale_factor", 0f)
    set(value) = setFloat("density_scale_factor", value)

fun SettingsManager.densityScaleFlow(default: Float = 0f): Flow<Float> = getFloatFlow("density_scale_factor", default)

var SettingsManager.customDensityScale: Float
    get() = getFloat("custom_density_scale_value", 0f)
    set(value) = setFloat("custom_density_scale_value", value)

fun SettingsManager.customDensityScaleFlow(default: Float = 0f): Flow<Float> = getFloatFlow("custom_density_scale_value", default)

var SettingsManager.defaultOpenTab: String
    get() = getString("defaultOpenTab", "")
    set(value) = setString("defaultOpenTab", value)

fun SettingsManager.defaultOpenTabFlow(default: String = ""): Flow<String> = getStringFlow("defaultOpenTab", default)

var SettingsManager.slimNavBar: Boolean
    get() = getBoolean("slimNavBar", false)
    set(value) = setBoolean("slimNavBar", value)

fun SettingsManager.slimNavBarFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("slimNavBar", default)

var SettingsManager.gridItemsSize: String
    get() = getString("gridItemSize", "")
    set(value) = setString("gridItemSize", value)

fun SettingsManager.gridItemsSizeFlow(default: String = ""): Flow<String> = getStringFlow("gridItemSize", default)

var SettingsManager.sliderStyle: String
    get() = getString("sliderStyle", "")
    set(value) = setString("sliderStyle", value)

fun SettingsManager.sliderStyleFlow(default: String = ""): Flow<String> = getStringFlow("sliderStyle", default)

var SettingsManager.squigglySlider: Boolean
    get() = getBoolean("squigglySlider", false)
    set(value) = setBoolean("squigglySlider", value)

fun SettingsManager.squigglySliderFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("squigglySlider", default)

var SettingsManager.swipeToSong: Boolean
    get() = getBoolean("SwipeToSong", false)
    set(value) = setBoolean("SwipeToSong", value)

fun SettingsManager.swipeToSongFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("SwipeToSong", default)

var SettingsManager.swipeToRemoveSong: Boolean
    get() = getBoolean("SwipeToRemoveSong", false)
    set(value) = setBoolean("SwipeToRemoveSong", value)

fun SettingsManager.swipeToRemoveSongFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("SwipeToRemoveSong", default)

var SettingsManager.useNewPlayerDesign: Boolean
    get() = getBoolean("useNewPlayerDesign", false)
    set(value) = setBoolean("useNewPlayerDesign", value)

fun SettingsManager.useNewPlayerDesignFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("useNewPlayerDesign", default)

var SettingsManager.useNewMiniPlayerDesign: Boolean
    get() = getBoolean("useNewMiniPlayerDesign", false)
    set(value) = setBoolean("useNewMiniPlayerDesign", value)

fun SettingsManager.useNewMiniPlayerDesignFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("useNewMiniPlayerDesign", default)

var SettingsManager.showCodecOnPlayer: Boolean
    get() = getBoolean("showCodecOnPlayer", false)
    set(value) = setBoolean("showCodecOnPlayer", value)

fun SettingsManager.showCodecOnPlayerFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("showCodecOnPlayer", default)

var SettingsManager.hidePlayerSlider: Boolean
    get() = getBoolean("hidePlayerSlider", false)
    set(value) = setBoolean("hidePlayerSlider", value)

fun SettingsManager.hidePlayerSliderFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("hidePlayerSlider", default)

var SettingsManager.hidePlayerThumbnail: Boolean
    get() = getBoolean("hidePlayerThumbnail", false)
    set(value) = setBoolean("hidePlayerThumbnail", value)

fun SettingsManager.hidePlayerThumbnailFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("hidePlayerThumbnail", default)

var SettingsManager.thumbnailCornerRadius: Float
    get() = getFloat("thumbnailCornerRadius", 0f)
    set(value) = setFloat("thumbnailCornerRadius", value)

fun SettingsManager.thumbnailCornerRadiusFlow(default: Float = 0f): Flow<Float> = getFloatFlow("thumbnailCornerRadius", default)

var SettingsManager.cropAlbumArt: Boolean
    get() = getBoolean("cropAlbumArt", false)
    set(value) = setBoolean("cropAlbumArt", value)

fun SettingsManager.cropAlbumArtFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("cropAlbumArt", default)

var SettingsManager.seekExtraSeconds: Boolean
    get() = getBoolean("seekExtraSeconds", false)
    set(value) = setBoolean("seekExtraSeconds", value)

fun SettingsManager.seekExtraSecondsFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("seekExtraSeconds", default)

var SettingsManager.pauseOnMute: Boolean
    get() = getBoolean("pauseOnMute", false)
    set(value) = setBoolean("pauseOnMute", value)

fun SettingsManager.pauseOnMuteFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("pauseOnMute", default)

var SettingsManager.resumeOnBluetoothConnect: Boolean
    get() = getBoolean("resumeOnBluetoothConnect", false)
    set(value) = setBoolean("resumeOnBluetoothConnect", value)

fun SettingsManager.resumeOnBluetoothConnectFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("resumeOnBluetoothConnect", default)

var SettingsManager.keepScreenOn: Boolean
    get() = getBoolean("keepScreenOn", false)
    set(value) = setBoolean("keepScreenOn", value)

fun SettingsManager.keepScreenOnFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("keepScreenOn", default)

var SettingsManager.developerMode: Boolean
    get() = getBoolean("developerMode", false)
    set(value) = setBoolean("developerMode", value)

fun SettingsManager.developerModeFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("developerMode", default)

var SettingsManager.appLanguage: String
    get() = getString("appLanguage", "")
    set(value) = setString("appLanguage", value)

fun SettingsManager.appLanguageFlow(default: String = ""): Flow<String> = getStringFlow("appLanguage", default)

var SettingsManager.contentLanguage: String
    get() = getString("contentLanguage", "")
    set(value) = setString("contentLanguage", value)

fun SettingsManager.contentLanguageFlow(default: String = ""): Flow<String> = getStringFlow("contentLanguage", default)

var SettingsManager.contentCountry: String
    get() = getString("contentCountry", "")
    set(value) = setString("contentCountry", value)

fun SettingsManager.contentCountryFlow(default: String = ""): Flow<String> = getStringFlow("contentCountry", default)

var SettingsManager.suggestionRegion: String
    get() = getString("suggestionRegion", "")
    set(value) = setString("suggestionRegion", value)

fun SettingsManager.suggestionRegionFlow(default: String = ""): Flow<String> = getStringFlow("suggestionRegion", default)

var SettingsManager.enableKugou: Boolean
    get() = getBoolean("enableKugou", false)
    set(value) = setBoolean("enableKugou", value)

fun SettingsManager.enableKugouFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("enableKugou", default)

var SettingsManager.fetchFasterLyrics: Boolean
    get() = getBoolean("fetchFasterLyrics", false)
    set(value) = setBoolean("fetchFasterLyrics", value)

fun SettingsManager.fetchFasterLyricsFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("fetchFasterLyrics", default)

var SettingsManager.enableLrcLib: Boolean
    get() = getBoolean("enableLrclib", false)
    set(value) = setBoolean("enableLrclib", value)

fun SettingsManager.enableLrcLibFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("enableLrclib", default)

var SettingsManager.enableBetterLyrics: Boolean
    get() = getBoolean("enableBetterLyrics", false)
    set(value) = setBoolean("enableBetterLyrics", value)

fun SettingsManager.enableBetterLyricsFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("enableBetterLyrics", default)

var SettingsManager.enableSimpMusic: Boolean
    get() = getBoolean("enableSimpMusic", false)
    set(value) = setBoolean("enableSimpMusic", value)

fun SettingsManager.enableSimpMusicFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("enableSimpMusic", default)

var SettingsManager.enableYouLyPlus: Boolean
    get() = getBoolean("enableYouLyPlus", false)
    set(value) = setBoolean("enableYouLyPlus", value)

fun SettingsManager.enableYouLyPlusFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("enableYouLyPlus", default)

var SettingsManager.enablePaxsenix: Boolean
    get() = getBoolean("enablePaxsenix", false)
    set(value) = setBoolean("enablePaxsenix", value)

fun SettingsManager.enablePaxsenixFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("enablePaxsenix", default)

var SettingsManager.hideExplicit: Boolean
    get() = getBoolean("hideExplicit", false)
    set(value) = setBoolean("hideExplicit", value)

fun SettingsManager.hideExplicitFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("hideExplicit", default)

var SettingsManager.sponsorBlockEnabled: Boolean
    get() = getBoolean("sponsor_block_enabled", false)
    set(value) = setBoolean("sponsor_block_enabled", value)

fun SettingsManager.sponsorBlockEnabledFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("sponsor_block_enabled", default)

var SettingsManager.hideVideoSongs: Boolean
    get() = getBoolean("hideVideoSongs", false)
    set(value) = setBoolean("hideVideoSongs", value)

fun SettingsManager.hideVideoSongsFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("hideVideoSongs", default)

var SettingsManager.hideYoutubeShorts: Boolean
    get() = getBoolean("hideYoutubeShorts", false)
    set(value) = setBoolean("hideYoutubeShorts", value)

fun SettingsManager.hideYoutubeShortsFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("hideYoutubeShorts", default)

var SettingsManager.showArtistDescription: Boolean
    get() = getBoolean("showArtistDescription", false)
    set(value) = setBoolean("showArtistDescription", value)

fun SettingsManager.showArtistDescriptionFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("showArtistDescription", default)

var SettingsManager.showArtistSubscriberCount: Boolean
    get() = getBoolean("showArtistSubscriberCount", false)
    set(value) = setBoolean("showArtistSubscriberCount", value)

fun SettingsManager.showArtistSubscriberCountFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("showArtistSubscriberCount", default)

var SettingsManager.showMonthlyListeners: Boolean
    get() = getBoolean("showMonthlyListeners", false)
    set(value) = setBoolean("showMonthlyListeners", value)

fun SettingsManager.showMonthlyListenersFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("showMonthlyListeners", default)

var SettingsManager.showArtistVideo: Boolean
    get() = getBoolean("showArtistVideo", false)
    set(value) = setBoolean("showArtistVideo", value)

fun SettingsManager.showArtistVideoFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("showArtistVideo", default)

var SettingsManager.showArtistBackgroundVideo: Boolean
    get() = getBoolean("showArtistBackgroundVideo", false)
    set(value) = setBoolean("showArtistBackgroundVideo", value)

fun SettingsManager.showArtistBackgroundVideoFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("showArtistBackgroundVideo", default)

var SettingsManager.proxyEnabled: Boolean
    get() = getBoolean("proxyEnabled", false)
    set(value) = setBoolean("proxyEnabled", value)

fun SettingsManager.proxyEnabledFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("proxyEnabled", default)

var SettingsManager.proxyUrl: String
    get() = getString("proxyUrl", "")
    set(value) = setString("proxyUrl", value)

fun SettingsManager.proxyUrlFlow(default: String = ""): Flow<String> = getStringFlow("proxyUrl", default)

var SettingsManager.proxyType: String
    get() = getString("proxyType", "")
    set(value) = setString("proxyType", value)

fun SettingsManager.proxyTypeFlow(default: String = ""): Flow<String> = getStringFlow("proxyType", default)

var SettingsManager.proxyUsername: String
    get() = getString("proxyUsername", "")
    set(value) = setString("proxyUsername", value)

fun SettingsManager.proxyUsernameFlow(default: String = ""): Flow<String> = getStringFlow("proxyUsername", default)

var SettingsManager.proxyPassword: String
    get() = getString("proxyPassword", "")
    set(value) = setString("proxyPassword", value)

fun SettingsManager.proxyPasswordFlow(default: String = ""): Flow<String> = getStringFlow("proxyPassword", default)

var SettingsManager.ytmSync: Boolean
    get() = getBoolean("ytmSync", false)
    set(value) = setBoolean("ytmSync", value)

fun SettingsManager.ytmSyncFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("ytmSync", default)

var SettingsManager.selectedYtmPlaylists: String
    get() = getString("selectedYtmPlaylists", "")
    set(value) = setString("selectedYtmPlaylists", value)

fun SettingsManager.selectedYtmPlaylistsFlow(default: String = ""): Flow<String> = getStringFlow("selectedYtmPlaylists", default)

var SettingsManager.showAudioFallbackToast: Boolean
    get() = getBoolean("show_audio_fallback_toast", false)
    set(value) = setBoolean("show_audio_fallback_toast", value)

fun SettingsManager.showAudioFallbackToastFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("show_audio_fallback_toast", default)

var SettingsManager.audioQuality: String
    get() = getString("audioQuality", "")
    set(value) = setString("audioQuality", value)

fun SettingsManager.audioQualityFlow(default: String = ""): Flow<String> = getStringFlow("audioQuality", default)

var SettingsManager.ipVersion: String
    get() = getString("ipVersion", "")
    set(value) = setString("ipVersion", value)

fun SettingsManager.ipVersionFlow(default: String = ""): Flow<String> = getStringFlow("ipVersion", default)

var SettingsManager.downloadQuality: String
    get() = getString("downloadQuality", "")
    set(value) = setString("downloadQuality", value)

fun SettingsManager.downloadQualityFlow(default: String = ""): Flow<String> = getStringFlow("downloadQuality", default)

var SettingsManager.downloadOnWifiOnly: Boolean
    get() = getBoolean("downloadOnWifiOnly", false)
    set(value) = setBoolean("downloadOnWifiOnly", value)

fun SettingsManager.downloadOnWifiOnlyFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("downloadOnWifiOnly", default)

var SettingsManager.audioOffload: Boolean
    get() = getBoolean("enableOffload", false)
    set(value) = setBoolean("enableOffload", value)

fun SettingsManager.audioOffloadFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("enableOffload", default)

var SettingsManager.spatialAudio: Boolean
    get() = getBoolean("spatialAudio", false)
    set(value) = setBoolean("spatialAudio", value)

fun SettingsManager.spatialAudioFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("spatialAudio", default)

var SettingsManager.audioLoudnessPreset: String
    get() = getString("audioLoudnessPreset", "")
    set(value) = setString("audioLoudnessPreset", value)

fun SettingsManager.audioLoudnessPresetFlow(default: String = ""): Flow<String> = getStringFlow("audioLoudnessPreset", default)

var SettingsManager.playbackEngine: String
    get() = getString("playbackEngine", "")
    set(value) = setString("playbackEngine", value)

fun SettingsManager.playbackEngineFlow(default: String = ""): Flow<String> = getStringFlow("playbackEngine", default)

var SettingsManager.persistentQueue: Boolean
    get() = getBoolean("persistentQueue", false)
    set(value) = setBoolean("persistentQueue", value)

fun SettingsManager.persistentQueueFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("persistentQueue", default)

var SettingsManager.persistentShuffleAcrossQueues: Boolean
    get() = getBoolean("persistentShuffleAcrossQueues", false)
    set(value) = setBoolean("persistentShuffleAcrossQueues", value)

fun SettingsManager.persistentShuffleAcrossQueuesFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("persistentShuffleAcrossQueues", default)

var SettingsManager.rememberShuffleAndRepeat: Boolean
    get() = getBoolean("rememberShuffleAndRepeat", false)
    set(value) = setBoolean("rememberShuffleAndRepeat", value)

fun SettingsManager.rememberShuffleAndRepeatFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("rememberShuffleAndRepeat", default)

var SettingsManager.shuffleMode: Boolean
    get() = getBoolean("shuffleMode", false)
    set(value) = setBoolean("shuffleMode", value)

fun SettingsManager.shuffleModeFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("shuffleMode", default)

var SettingsManager.skipSilence: Boolean
    get() = getBoolean("skipSilence", false)
    set(value) = setBoolean("skipSilence", value)

fun SettingsManager.skipSilenceFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("skipSilence", default)

var SettingsManager.skipSilenceInstant: Boolean
    get() = getBoolean("skipSilenceInstant", false)
    set(value) = setBoolean("skipSilenceInstant", value)

fun SettingsManager.skipSilenceInstantFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("skipSilenceInstant", default)

var SettingsManager.audioNormalization: Boolean
    get() = getBoolean("audioNormalization", false)
    set(value) = setBoolean("audioNormalization", value)

fun SettingsManager.audioNormalizationFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("audioNormalization", default)

var SettingsManager.autoLoadMore: Boolean
    get() = getBoolean("autoLoadMore", false)
    set(value) = setBoolean("autoLoadMore", value)

fun SettingsManager.autoLoadMoreFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("autoLoadMore", default)

var SettingsManager.disableLoadMoreWhenRepeatAll: Boolean
    get() = getBoolean("disableLoadMoreWhenRepeatAll", false)
    set(value) = setBoolean("disableLoadMoreWhenRepeatAll", value)

fun SettingsManager.disableLoadMoreWhenRepeatAllFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("disableLoadMoreWhenRepeatAll", default)

var SettingsManager.autoDownloadOnLike: Boolean
    get() = getBoolean("autoDownloadOnLike", false)
    set(value) = setBoolean("autoDownloadOnLike", value)

fun SettingsManager.autoDownloadOnLikeFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("autoDownloadOnLike", default)

var SettingsManager.similarContent: Boolean
    get() = getBoolean("similarContent", false)
    set(value) = setBoolean("similarContent", value)

fun SettingsManager.similarContentFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("similarContent", default)

var SettingsManager.autoSkipNextOnError: Boolean
    get() = getBoolean("autoSkipNextOnError", false)
    set(value) = setBoolean("autoSkipNextOnError", value)

fun SettingsManager.autoSkipNextOnErrorFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("autoSkipNextOnError", default)

var SettingsManager.stopMusicOnTaskClear: Boolean
    get() = getBoolean("stopMusicOnTaskClear", false)
    set(value) = setBoolean("stopMusicOnTaskClear", value)

fun SettingsManager.stopMusicOnTaskClearFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("stopMusicOnTaskClear", default)

var SettingsManager.shufflePlaylistFirst: Boolean
    get() = getBoolean("shufflePlaylistFirst", false)
    set(value) = setBoolean("shufflePlaylistFirst", value)

fun SettingsManager.shufflePlaylistFirstFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("shufflePlaylistFirst", default)

var SettingsManager.preventDuplicateTracksInQueue: Boolean
    get() = getBoolean("preventDuplicateTracksInQueue", false)
    set(value) = setBoolean("preventDuplicateTracksInQueue", value)

fun SettingsManager.preventDuplicateTracksInQueueFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("preventDuplicateTracksInQueue", default)

var SettingsManager.crossfadeEnabled: Boolean
    get() = getBoolean("crossfadeEnabled", false)
    set(value) = setBoolean("crossfadeEnabled", value)

fun SettingsManager.crossfadeEnabledFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("crossfadeEnabled", default)

var SettingsManager.crossfadeDuration: Float
    get() = getFloat("crossfadeDuration", 0f)
    set(value) = setFloat("crossfadeDuration", value)

fun SettingsManager.crossfadeDurationFlow(default: Float = 0f): Flow<Float> = getFloatFlow("crossfadeDuration", default)

var SettingsManager.crossfadeGapless: Boolean
    get() = getBoolean("crossfadeGapless", false)
    set(value) = setBoolean("crossfadeGapless", value)

fun SettingsManager.crossfadeGaplessFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("crossfadeGapless", default)

var SettingsManager.automixCrossfade: Boolean
    get() = getBoolean("automixCrossfade", false)
    set(value) = setBoolean("automixCrossfade", value)

fun SettingsManager.automixCrossfadeFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("automixCrossfade", default)

var SettingsManager.automixDebugOverlay: Boolean
    get() = getBoolean("automixDebugOverlay", false)
    set(value) = setBoolean("automixDebugOverlay", value)

fun SettingsManager.automixDebugOverlayFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("automixDebugOverlay", default)

var SettingsManager.maxImageCacheSize: Int
    get() = getInt("maxImageCacheSize", 0)
    set(value) = setInt("maxImageCacheSize", value)

fun SettingsManager.maxImageCacheSizeFlow(default: Int = 0): Flow<Int> = getIntFlow("maxImageCacheSize", default)

var SettingsManager.maxSongCacheSize: Int
    get() = getInt("maxSongCacheSize", 0)
    set(value) = setInt("maxSongCacheSize", value)

fun SettingsManager.maxSongCacheSizeFlow(default: Int = 0): Flow<Int> = getIntFlow("maxSongCacheSize", default)

var SettingsManager.exportDirectoryUri: String
    get() = getString("exportDirectoryUri", "")
    set(value) = setString("exportDirectoryUri", value)

fun SettingsManager.exportDirectoryUriFlow(default: String = ""): Flow<String> = getStringFlow("exportDirectoryUri", default)

var SettingsManager.exportingSongIds: String
    get() = getString("exportingSongIds", "")
    set(value) = setString("exportingSongIds", value)

fun SettingsManager.exportingSongIdsFlow(default: String = ""): Flow<String> = getStringFlow("exportingSongIds", default)

var SettingsManager.exportedSongIds: String
    get() = getString("exportedSongIds", "")
    set(value) = setString("exportedSongIds", value)

fun SettingsManager.exportedSongIdsFlow(default: String = ""): Flow<String> = getStringFlow("exportedSongIds", default)

var SettingsManager.exportProgress: String
    get() = getString("exportProgress", "")
    set(value) = setString("exportProgress", value)

fun SettingsManager.exportProgressFlow(default: String = ""): Flow<String> = getStringFlow("exportProgress", default)

var SettingsManager.enableExportAsMp3: Boolean
    get() = getBoolean("enableExportAsMp3", false)
    set(value) = setBoolean("enableExportAsMp3", value)

fun SettingsManager.enableExportAsMp3Flow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("enableExportAsMp3", default)

var SettingsManager.pauseListenHistory: Boolean
    get() = getBoolean("pauseListenHistory", false)
    set(value) = setBoolean("pauseListenHistory", value)

fun SettingsManager.pauseListenHistoryFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("pauseListenHistory", default)

var SettingsManager.pauseSearchHistory: Boolean
    get() = getBoolean("pauseSearchHistory", false)
    set(value) = setBoolean("pauseSearchHistory", value)

fun SettingsManager.pauseSearchHistoryFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("pauseSearchHistory", default)

var SettingsManager.disableScreenshot: Boolean
    get() = getBoolean("disableScreenshot", false)
    set(value) = setBoolean("disableScreenshot", value)

fun SettingsManager.disableScreenshotFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("disableScreenshot", default)

var SettingsManager.enableGoogleCast: Boolean
    get() = getBoolean("enableGoogleCast", false)
    set(value) = setBoolean("enableGoogleCast", value)

fun SettingsManager.enableGoogleCastFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("enableGoogleCast", default)

var SettingsManager.listenTogetherServerUrl: String
    get() = getString("listenTogetherServerUrl", "")
    set(value) = setString("listenTogetherServerUrl", value)

fun SettingsManager.listenTogetherServerUrlFlow(default: String = ""): Flow<String> = getStringFlow("listenTogetherServerUrl", default)

var SettingsManager.listenTogetherUsername: String
    get() = getString("listenTogetherUsername", "")
    set(value) = setString("listenTogetherUsername", value)

fun SettingsManager.listenTogetherUsernameFlow(default: String = ""): Flow<String> = getStringFlow("listenTogetherUsername", default)

var SettingsManager.enableListenTogether: Boolean
    get() = getBoolean("enableListenTogether", false)
    set(value) = setBoolean("enableListenTogether", value)

fun SettingsManager.enableListenTogetherFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("enableListenTogether", default)

var SettingsManager.listenTogetherAutoApproval: Boolean
    get() = getBoolean("listenTogetherAutoApproval", false)
    set(value) = setBoolean("listenTogetherAutoApproval", value)

fun SettingsManager.listenTogetherAutoApprovalFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("listenTogetherAutoApproval", default)

var SettingsManager.listenTogetherSyncVolume: Boolean
    get() = getBoolean("listenTogetherSyncVolume", false)
    set(value) = setBoolean("listenTogetherSyncVolume", value)

fun SettingsManager.listenTogetherSyncVolumeFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("listenTogetherSyncVolume", default)

var SettingsManager.listenTogetherSmartResync: Boolean
    get() = getBoolean("listenTogetherSmartResync", false)
    set(value) = setBoolean("listenTogetherSmartResync", value)

fun SettingsManager.listenTogetherSmartResyncFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("listenTogetherSmartResync", default)

var SettingsManager.listenTogetherBlockedUsers: String
    get() = getString("listenTogetherBlockedUsers", "")
    set(value) = setString("listenTogetherBlockedUsers", value)

fun SettingsManager.listenTogetherBlockedUsersFlow(default: String = ""): Flow<String> = getStringFlow("listenTogetherBlockedUsers", default)

var SettingsManager.listenTogetherInTopBar: Boolean
    get() = getBoolean("listenTogetherInTopBar", false)
    set(value) = setBoolean("listenTogetherInTopBar", value)

fun SettingsManager.listenTogetherInTopBarFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("listenTogetherInTopBar", default)

var SettingsManager.listenTogetherSessionToken: String
    get() = getString("listenTogetherSessionToken", "")
    set(value) = setString("listenTogetherSessionToken", value)

fun SettingsManager.listenTogetherSessionTokenFlow(default: String = ""): Flow<String> = getStringFlow("listenTogetherSessionToken", default)

var SettingsManager.listenTogetherRoomCode: String
    get() = getString("listenTogetherRoomCode", "")
    set(value) = setString("listenTogetherRoomCode", value)

fun SettingsManager.listenTogetherRoomCodeFlow(default: String = ""): Flow<String> = getStringFlow("listenTogetherRoomCode", default)

var SettingsManager.listenTogetherUserId: String
    get() = getString("listenTogetherUserId", "")
    set(value) = setString("listenTogetherUserId", value)

fun SettingsManager.listenTogetherUserIdFlow(default: String = ""): Flow<String> = getStringFlow("listenTogetherUserId", default)

var SettingsManager.listenTogetherIsHost: Boolean
    get() = getBoolean("listenTogetherIsHost", false)
    set(value) = setBoolean("listenTogetherIsHost", value)

fun SettingsManager.listenTogetherIsHostFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("listenTogetherIsHost", default)

var SettingsManager.listenTogetherSessionTimestamp: Long
    get() = getLong("listenTogetherSessionTimestamp", 0L)
    set(value) = setLong("listenTogetherSessionTimestamp", value)

fun SettingsManager.listenTogetherSessionTimestampFlow(default: Long = 0L): Flow<Long> = getLongFlow("listenTogetherSessionTimestamp", default)

var SettingsManager.lastFMSession: String
    get() = getString("lastfmSession", "")
    set(value) = setString("lastfmSession", value)

fun SettingsManager.lastFMSessionFlow(default: String = ""): Flow<String> = getStringFlow("lastfmSession", default)

var SettingsManager.lastFMUsername: String
    get() = getString("lastfmUsername", "")
    set(value) = setString("lastfmUsername", value)

fun SettingsManager.lastFMUsernameFlow(default: String = ""): Flow<String> = getStringFlow("lastfmUsername", default)

var SettingsManager.enableLastFMScrobbling: Boolean
    get() = getBoolean("lastfmScrobblingEnable", false)
    set(value) = setBoolean("lastfmScrobblingEnable", value)

fun SettingsManager.enableLastFMScrobblingFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("lastfmScrobblingEnable", default)

var SettingsManager.lastFMUseNowPlaying: Boolean
    get() = getBoolean("lastfmUseNowPlaying", false)
    set(value) = setBoolean("lastfmUseNowPlaying", value)

fun SettingsManager.lastFMUseNowPlayingFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("lastfmUseNowPlaying", default)

var SettingsManager.lastFMUseSendLikes: Boolean
    get() = getBoolean("lastfmUseSendLikes", false)
    set(value) = setBoolean("lastfmUseSendLikes", value)

fun SettingsManager.lastFMUseSendLikesFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("lastfmUseSendLikes", default)

var SettingsManager.scrobbleDelayPercent: Float
    get() = getFloat("scrobbleDelayPercent", 0f)
    set(value) = setFloat("scrobbleDelayPercent", value)

fun SettingsManager.scrobbleDelayPercentFlow(default: Float = 0f): Flow<Float> = getFloatFlow("scrobbleDelayPercent", default)

var SettingsManager.scrobbleMinSongDuration: Int
    get() = getInt("scrobbleMinSongDuration", 0)
    set(value) = setInt("scrobbleMinSongDuration", value)

fun SettingsManager.scrobbleMinSongDurationFlow(default: Int = 0): Flow<Int> = getIntFlow("scrobbleMinSongDuration", default)

var SettingsManager.scrobbleDelaySeconds: Int
    get() = getInt("scrobbleDelaySeconds", 0)
    set(value) = setInt("scrobbleDelaySeconds", value)

fun SettingsManager.scrobbleDelaySecondsFlow(default: Int = 0): Flow<Int> = getIntFlow("scrobbleDelaySeconds", default)

var SettingsManager.chipSortType: String
    get() = getString("chipSortType", "")
    set(value) = setString("chipSortType", value)

fun SettingsManager.chipSortTypeFlow(default: String = ""): Flow<String> = getStringFlow("chipSortType", default)

var SettingsManager.songSortType: String
    get() = getString("songSortType", "")
    set(value) = setString("songSortType", value)

fun SettingsManager.songSortTypeFlow(default: String = ""): Flow<String> = getStringFlow("songSortType", default)

var SettingsManager.songSortDescending: Boolean
    get() = getBoolean("songSortDescending", false)
    set(value) = setBoolean("songSortDescending", value)

fun SettingsManager.songSortDescendingFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("songSortDescending", default)

var SettingsManager.playlistSongSortType: String
    get() = getString("playlistSongSortType", "")
    set(value) = setString("playlistSongSortType", value)

fun SettingsManager.playlistSongSortTypeFlow(default: String = ""): Flow<String> = getStringFlow("playlistSongSortType", default)

var SettingsManager.playlistSongSortDescending: Boolean
    get() = getBoolean("playlistSongSortDescending", false)
    set(value) = setBoolean("playlistSongSortDescending", value)

fun SettingsManager.playlistSongSortDescendingFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("playlistSongSortDescending", default)

var SettingsManager.autoPlaylistSongSortType: String
    get() = getString("autoPlaylistSongSortType", "")
    set(value) = setString("autoPlaylistSongSortType", value)

fun SettingsManager.autoPlaylistSongSortTypeFlow(default: String = ""): Flow<String> = getStringFlow("autoPlaylistSongSortType", default)

var SettingsManager.autoPlaylistSongSortDescending: Boolean
    get() = getBoolean("autoPlaylistSongSortDescending", false)
    set(value) = setBoolean("autoPlaylistSongSortDescending", value)

fun SettingsManager.autoPlaylistSongSortDescendingFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("autoPlaylistSongSortDescending", default)

var SettingsManager.artistSortType: String
    get() = getString("artistSortType", "")
    set(value) = setString("artistSortType", value)

fun SettingsManager.artistSortTypeFlow(default: String = ""): Flow<String> = getStringFlow("artistSortType", default)

var SettingsManager.artistSortDescending: Boolean
    get() = getBoolean("artistSortDescending", false)
    set(value) = setBoolean("artistSortDescending", value)

fun SettingsManager.artistSortDescendingFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("artistSortDescending", default)

var SettingsManager.albumSortType: String
    get() = getString("albumSortType", "")
    set(value) = setString("albumSortType", value)

fun SettingsManager.albumSortTypeFlow(default: String = ""): Flow<String> = getStringFlow("albumSortType", default)

var SettingsManager.albumSortDescending: Boolean
    get() = getBoolean("albumSortDescending", false)
    set(value) = setBoolean("albumSortDescending", value)

fun SettingsManager.albumSortDescendingFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("albumSortDescending", default)

var SettingsManager.playlistSortType: String
    get() = getString("playlistSortType", "")
    set(value) = setString("playlistSortType", value)

fun SettingsManager.playlistSortTypeFlow(default: String = ""): Flow<String> = getStringFlow("playlistSortType", default)

var SettingsManager.playlistSortDescending: Boolean
    get() = getBoolean("playlistSortDescending", false)
    set(value) = setBoolean("playlistSortDescending", value)

fun SettingsManager.playlistSortDescendingFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("playlistSortDescending", default)

var SettingsManager.addToPlaylistSortType: String
    get() = getString("addToPlaylistSortType", "")
    set(value) = setString("addToPlaylistSortType", value)

fun SettingsManager.addToPlaylistSortTypeFlow(default: String = ""): Flow<String> = getStringFlow("addToPlaylistSortType", default)

var SettingsManager.addToPlaylistSortDescending: Boolean
    get() = getBoolean("addToPlaylistSortDescending", false)
    set(value) = setBoolean("addToPlaylistSortDescending", value)

fun SettingsManager.addToPlaylistSortDescendingFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("addToPlaylistSortDescending", default)

var SettingsManager.artistSongSortType: String
    get() = getString("artistSongSortType", "")
    set(value) = setString("artistSongSortType", value)

fun SettingsManager.artistSongSortTypeFlow(default: String = ""): Flow<String> = getStringFlow("artistSongSortType", default)

var SettingsManager.artistSongSortDescending: Boolean
    get() = getBoolean("artistSongSortDescending", false)
    set(value) = setBoolean("artistSongSortDescending", value)

fun SettingsManager.artistSongSortDescendingFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("artistSongSortDescending", default)

var SettingsManager.mixSortType: String
    get() = getString("mixSortType", "")
    set(value) = setString("mixSortType", value)

fun SettingsManager.mixSortTypeFlow(default: String = ""): Flow<String> = getStringFlow("mixSortType", default)

var SettingsManager.mixSortDescending: Boolean
    get() = getBoolean("albumSortDescending", false)
    set(value) = setBoolean("albumSortDescending", value)

fun SettingsManager.mixSortDescendingFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("albumSortDescending", default)

var SettingsManager.localSongsMinDurationSeconds: Int
    get() = getInt("local_songs_min_duration_seconds", 0)
    set(value) = setInt("local_songs_min_duration_seconds", value)

fun SettingsManager.localSongsMinDurationSecondsFlow(default: Int = 0): Flow<Int> = getIntFlow("local_songs_min_duration_seconds", default)

var SettingsManager.localSongsExcludedFolders: String
    get() = getString("local_songs_excluded_folders", "")
    set(value) = setString("local_songs_excluded_folders", value)

fun SettingsManager.localSongsExcludedFoldersFlow(default: String = ""): Flow<String> = getStringFlow("local_songs_excluded_folders", default)

var SettingsManager.localStorageDirs: String
    get() = getString("local_storage_dirs", "")
    set(value) = setString("local_storage_dirs", value)

fun SettingsManager.localStorageDirsFlow(default: String = ""): Flow<String> = getStringFlow("local_storage_dirs", default)

var SettingsManager.discordToken: String
    get() = getString("discord_token", "")
    set(value) = setString("discord_token", value)

fun SettingsManager.discordTokenFlow(default: String = ""): Flow<String> = getStringFlow("discord_token", default)

var SettingsManager.discordRefreshToken: String
    get() = getString("discord_refresh_token", "")
    set(value) = setString("discord_refresh_token", value)

fun SettingsManager.discordRefreshTokenFlow(default: String = ""): Flow<String> = getStringFlow("discord_refresh_token", default)

var SettingsManager.discordTokenExpiresAt: Long
    get() = getLong("discord_token_expires_at", 0L)
    set(value) = setLong("discord_token_expires_at", value)

fun SettingsManager.discordTokenExpiresAtFlow(default: Long = 0L): Flow<Long> = getLongFlow("discord_token_expires_at", default)

var SettingsManager.discordName: String
    get() = getString("discord_name", "")
    set(value) = setString("discord_name", value)

fun SettingsManager.discordNameFlow(default: String = ""): Flow<String> = getStringFlow("discord_name", default)

var SettingsManager.discordUsername: String
    get() = getString("discord_username", "")
    set(value) = setString("discord_username", value)

fun SettingsManager.discordUsernameFlow(default: String = ""): Flow<String> = getStringFlow("discord_username", default)

var SettingsManager.discordAvatarUrl: String
    get() = getString("discord_avatar_url", "")
    set(value) = setString("discord_avatar_url", value)

fun SettingsManager.discordAvatarUrlFlow(default: String = ""): Flow<String> = getStringFlow("discord_avatar_url", default)

var SettingsManager.enableDiscordRPC: Boolean
    get() = getBoolean("enable_discord_rpc", false)
    set(value) = setBoolean("enable_discord_rpc", value)

fun SettingsManager.enableDiscordRPCFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("enable_discord_rpc", default)

var SettingsManager.discordShowWhenPaused: Boolean
    get() = getBoolean("discord_show_when_paused", false)
    set(value) = setBoolean("discord_show_when_paused", value)

fun SettingsManager.discordShowWhenPausedFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("discord_show_when_paused", default)

var SettingsManager.discordPresenceStatus: String
    get() = getString("discord_presence_status", "")
    set(value) = setString("discord_presence_status", value)

fun SettingsManager.discordPresenceStatusFlow(default: String = ""): Flow<String> = getStringFlow("discord_presence_status", default)

var SettingsManager.discordActivityType: String
    get() = getString("discord_activity_type", "")
    set(value) = setString("discord_activity_type", value)

fun SettingsManager.discordActivityTypeFlow(default: String = ""): Flow<String> = getStringFlow("discord_activity_type", default)

var SettingsManager.discordActivityName: String
    get() = getString("discord_activity_name", "")
    set(value) = setString("discord_activity_name", value)

fun SettingsManager.discordActivityNameFlow(default: String = ""): Flow<String> = getStringFlow("discord_activity_name", default)

var SettingsManager.discordActivityDetails: String
    get() = getString("discord_activity_details", "")
    set(value) = setString("discord_activity_details", value)

fun SettingsManager.discordActivityDetailsFlow(default: String = ""): Flow<String> = getStringFlow("discord_activity_details", default)

var SettingsManager.discordActivityState: String
    get() = getString("discord_activity_state", "")
    set(value) = setString("discord_activity_state", value)

fun SettingsManager.discordActivityStateFlow(default: String = ""): Flow<String> = getStringFlow("discord_activity_state", default)

var SettingsManager.discordActivityPlatform: String
    get() = getString("discord_activity_platform", "")
    set(value) = setString("discord_activity_platform", value)

fun SettingsManager.discordActivityPlatformFlow(default: String = ""): Flow<String> = getStringFlow("discord_activity_platform", default)

var SettingsManager.discordLargeImageType: String
    get() = getString("discord_large_image_type", "")
    set(value) = setString("discord_large_image_type", value)

fun SettingsManager.discordLargeImageTypeFlow(default: String = ""): Flow<String> = getStringFlow("discord_large_image_type", default)

var SettingsManager.discordLargeImageCustomUrl: String
    get() = getString("discord_large_image_custom_url", "")
    set(value) = setString("discord_large_image_custom_url", value)

fun SettingsManager.discordLargeImageCustomUrlFlow(default: String = ""): Flow<String> = getStringFlow("discord_large_image_custom_url", default)

var SettingsManager.discordSmallImageType: String
    get() = getString("discord_small_image_type", "")
    set(value) = setString("discord_small_image_type", value)

fun SettingsManager.discordSmallImageTypeFlow(default: String = ""): Flow<String> = getStringFlow("discord_small_image_type", default)

var SettingsManager.discordSmallImageCustomUrl: String
    get() = getString("discord_small_image_custom_url", "")
    set(value) = setString("discord_small_image_custom_url", value)

fun SettingsManager.discordSmallImageCustomUrlFlow(default: String = ""): Flow<String> = getStringFlow("discord_small_image_custom_url", default)

var SettingsManager.discordActivityButton1Enabled: Boolean
    get() = getBoolean("discord_activity_button1_enabled", false)
    set(value) = setBoolean("discord_activity_button1_enabled", value)

fun SettingsManager.discordActivityButton1EnabledFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("discord_activity_button1_enabled", default)

var SettingsManager.discordActivityButton1Label: String
    get() = getString("discord_activity_button1_label", "")
    set(value) = setString("discord_activity_button1_label", value)

fun SettingsManager.discordActivityButton1LabelFlow(default: String = ""): Flow<String> = getStringFlow("discord_activity_button1_label", default)

var SettingsManager.discordActivityButton1UrlSource: String
    get() = getString("discord_activity_button1_url_source", "")
    set(value) = setString("discord_activity_button1_url_source", value)

fun SettingsManager.discordActivityButton1UrlSourceFlow(default: String = ""): Flow<String> = getStringFlow("discord_activity_button1_url_source", default)

var SettingsManager.discordActivityButton1CustomUrl: String
    get() = getString("discord_activity_button1_custom_url", "")
    set(value) = setString("discord_activity_button1_custom_url", value)

fun SettingsManager.discordActivityButton1CustomUrlFlow(default: String = ""): Flow<String> = getStringFlow("discord_activity_button1_custom_url", default)

var SettingsManager.discordActivityButton2Enabled: Boolean
    get() = getBoolean("discord_activity_button2_enabled", false)
    set(value) = setBoolean("discord_activity_button2_enabled", value)

fun SettingsManager.discordActivityButton2EnabledFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("discord_activity_button2_enabled", default)

var SettingsManager.discordActivityButton2Label: String
    get() = getString("discord_activity_button2_label", "")
    set(value) = setString("discord_activity_button2_label", value)

fun SettingsManager.discordActivityButton2LabelFlow(default: String = ""): Flow<String> = getStringFlow("discord_activity_button2_label", default)

var SettingsManager.discordActivityButton2UrlSource: String
    get() = getString("discord_activity_button2_url_source", "")
    set(value) = setString("discord_activity_button2_url_source", value)

fun SettingsManager.discordActivityButton2UrlSourceFlow(default: String = ""): Flow<String> = getStringFlow("discord_activity_button2_url_source", default)

var SettingsManager.discordActivityButton2CustomUrl: String
    get() = getString("discord_activity_button2_custom_url", "")
    set(value) = setString("discord_activity_button2_custom_url", value)

fun SettingsManager.discordActivityButton2CustomUrlFlow(default: String = ""): Flow<String> = getStringFlow("discord_activity_button2_custom_url", default)

var SettingsManager.localSongsSortType: String
    get() = getString("local_songs_sort_type", "")
    set(value) = setString("local_songs_sort_type", value)

fun SettingsManager.localSongsSortTypeFlow(default: String = ""): Flow<String> = getStringFlow("local_songs_sort_type", default)

var SettingsManager.localSongsSortDescending: Boolean
    get() = getBoolean("local_songs_sort_descending", false)
    set(value) = setBoolean("local_songs_sort_descending", value)

fun SettingsManager.localSongsSortDescendingFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("local_songs_sort_descending", default)

var SettingsManager.songFilter: String
    get() = getString("songFilter", "")
    set(value) = setString("songFilter", value)

fun SettingsManager.songFilterFlow(default: String = ""): Flow<String> = getStringFlow("songFilter", default)

var SettingsManager.artistFilter: String
    get() = getString("artistFilter", "")
    set(value) = setString("artistFilter", value)

fun SettingsManager.artistFilterFlow(default: String = ""): Flow<String> = getStringFlow("artistFilter", default)

var SettingsManager.albumFilter: String
    get() = getString("albumFilter", "")
    set(value) = setString("albumFilter", value)

fun SettingsManager.albumFilterFlow(default: String = ""): Flow<String> = getStringFlow("albumFilter", default)

var SettingsManager.lastLikeSongSync: Long
    get() = getLong("last_like_song_sync", 0L)
    set(value) = setLong("last_like_song_sync", value)

fun SettingsManager.lastLikeSongSyncFlow(default: Long = 0L): Flow<Long> = getLongFlow("last_like_song_sync", default)

var SettingsManager.lastLibSongSync: Long
    get() = getLong("last_library_song_sync", 0L)
    set(value) = setLong("last_library_song_sync", value)

fun SettingsManager.lastLibSongSyncFlow(default: Long = 0L): Flow<Long> = getLongFlow("last_library_song_sync", default)

var SettingsManager.lastAlbumSync: Long
    get() = getLong("last_album_sync", 0L)
    set(value) = setLong("last_album_sync", value)

fun SettingsManager.lastAlbumSyncFlow(default: Long = 0L): Flow<Long> = getLongFlow("last_album_sync", default)

var SettingsManager.lastArtistSync: Long
    get() = getLong("last_artist_sync", 0L)
    set(value) = setLong("last_artist_sync", value)

fun SettingsManager.lastArtistSyncFlow(default: Long = 0L): Flow<Long> = getLongFlow("last_artist_sync", default)

var SettingsManager.lastPlaylistSync: Long
    get() = getLong("last_playlist_sync", 0L)
    set(value) = setLong("last_playlist_sync", value)

fun SettingsManager.lastPlaylistSyncFlow(default: Long = 0L): Flow<Long> = getLongFlow("last_playlist_sync", default)

var SettingsManager.lastFullSync: Long
    get() = getLong("last_full_sync", 0L)
    set(value) = setLong("last_full_sync", value)

fun SettingsManager.lastFullSyncFlow(default: Long = 0L): Flow<Long> = getLongFlow("last_full_sync", default)

var SettingsManager.artistViewType: String
    get() = getString("artistViewType", "")
    set(value) = setString("artistViewType", value)

fun SettingsManager.artistViewTypeFlow(default: String = ""): Flow<String> = getStringFlow("artistViewType", default)

var SettingsManager.albumViewType: String
    get() = getString("albumViewType", "")
    set(value) = setString("albumViewType", value)

fun SettingsManager.albumViewTypeFlow(default: String = ""): Flow<String> = getStringFlow("albumViewType", default)

var SettingsManager.playlistViewType: String
    get() = getString("playlistViewType", "")
    set(value) = setString("playlistViewType", value)

fun SettingsManager.playlistViewTypeFlow(default: String = ""): Flow<String> = getStringFlow("playlistViewType", default)

var SettingsManager.playlistEditLock: Boolean
    get() = getBoolean("playlistEditLock", false)
    set(value) = setBoolean("playlistEditLock", value)

fun SettingsManager.playlistEditLockFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("playlistEditLock", default)

var SettingsManager.quickPicks: String
    get() = getString("discover", "")
    set(value) = setString("discover", value)

fun SettingsManager.quickPicksFlow(default: String = ""): Flow<String> = getStringFlow("discover", default)

var SettingsManager.preferredLyricsProvider: String
    get() = getString("lyricsProvider", "")
    set(value) = setString("lyricsProvider", value)

fun SettingsManager.preferredLyricsProviderFlow(default: String = ""): Flow<String> = getStringFlow("lyricsProvider", default)

var SettingsManager.lyricsProviderOrder: String
    get() = getString("lyricsProviderOrder", "")
    set(value) = setString("lyricsProviderOrder", value)

fun SettingsManager.lyricsProviderOrderFlow(default: String = ""): Flow<String> = getStringFlow("lyricsProviderOrder", default)

var SettingsManager.queueEditLock: Boolean
    get() = getBoolean("queueEditLockV2", false)
    set(value) = setBoolean("queueEditLockV2", value)

fun SettingsManager.queueEditLockFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("queueEditLockV2", default)

var SettingsManager.randomizeHomeOrder: Boolean
    get() = getBoolean("randomizeHomeOrder", false)
    set(value) = setBoolean("randomizeHomeOrder", value)

fun SettingsManager.randomizeHomeOrderFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("randomizeHomeOrder", default)

var SettingsManager.albumCanvasEnabled: Boolean
    get() = getBoolean("albumCanvasEnabled", false)
    set(value) = setBoolean("albumCanvasEnabled", value)

fun SettingsManager.albumCanvasEnabledFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("albumCanvasEnabled", default)

var SettingsManager.showLikedPlaylist: Boolean
    get() = getBoolean("show_liked_playlist", false)
    set(value) = setBoolean("show_liked_playlist", value)

fun SettingsManager.showLikedPlaylistFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("show_liked_playlist", default)

var SettingsManager.showDownloadedPlaylist: Boolean
    get() = getBoolean("show_downloaded_playlist", false)
    set(value) = setBoolean("show_downloaded_playlist", value)

fun SettingsManager.showDownloadedPlaylistFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("show_downloaded_playlist", default)

var SettingsManager.showExportedPlaylist: Boolean
    get() = getBoolean("show_exported_playlist", false)
    set(value) = setBoolean("show_exported_playlist", value)

fun SettingsManager.showExportedPlaylistFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("show_exported_playlist", default)

var SettingsManager.showTopPlaylist: Boolean
    get() = getBoolean("show_top_playlist", false)
    set(value) = setBoolean("show_top_playlist", value)

fun SettingsManager.showTopPlaylistFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("show_top_playlist", default)

var SettingsManager.showCachedPlaylist: Boolean
    get() = getBoolean("show_cached_playlist", false)
    set(value) = setBoolean("show_cached_playlist", value)

fun SettingsManager.showCachedPlaylistFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("show_cached_playlist", default)

var SettingsManager.showUploadedPlaylist: Boolean
    get() = getBoolean("show_uploaded_playlist", false)
    set(value) = setBoolean("show_uploaded_playlist", value)

fun SettingsManager.showUploadedPlaylistFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("show_uploaded_playlist", default)

var SettingsManager.enablePlayerSwipe: Boolean
    get() = getBoolean("enable_player_swipe", false)
    set(value) = setBoolean("enable_player_swipe", value)

fun SettingsManager.enablePlayerSwipeFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("enable_player_swipe", default)

var SettingsManager.showSpeedDial: Boolean
    get() = getBoolean("showSpeedDial", false)
    set(value) = setBoolean("showSpeedDial", value)

fun SettingsManager.showSpeedDialFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("showSpeedDial", default)

var SettingsManager.showCommentButton: Boolean
    get() = getBoolean("show_comment_button", false)
    set(value) = setBoolean("show_comment_button", value)

fun SettingsManager.showCommentButtonFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("show_comment_button", default)

var SettingsManager.topSize: String
    get() = getString("topSize", "")
    set(value) = setString("topSize", value)

fun SettingsManager.topSizeFlow(default: String = ""): Flow<String> = getStringFlow("topSize", default)

var SettingsManager.historyDuration: Float
    get() = getFloat("historyDuration", 0f)
    set(value) = setFloat("historyDuration", value)

fun SettingsManager.historyDurationFlow(default: Float = 0f): Flow<Float> = getFloatFlow("historyDuration", default)

var SettingsManager.playerButtonsStyle: String
    get() = getString("player_buttons_style", "")
    set(value) = setString("player_buttons_style", value)

fun SettingsManager.playerButtonsStyleFlow(default: String = ""): Flow<String> = getStringFlow("player_buttons_style", default)

var SettingsManager.playerBackgroundStyle: String
    get() = getString("playerBackgroundStyle", "")
    set(value) = setString("playerBackgroundStyle", value)

fun SettingsManager.playerBackgroundStyleFlow(default: String = ""): Flow<String> = getStringFlow("playerBackgroundStyle", default)

var SettingsManager.miniPlayerBackgroundStyle: String
    get() = getString("miniPlayerBackgroundStyle", "")
    set(value) = setString("miniPlayerBackgroundStyle", value)

fun SettingsManager.miniPlayerBackgroundStyleFlow(default: String = ""): Flow<String> = getStringFlow("miniPlayerBackgroundStyle", default)

var SettingsManager.showLyrics: Boolean
    get() = getBoolean("showLyrics", false)
    set(value) = setBoolean("showLyrics", value)

fun SettingsManager.showLyricsFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("showLyrics", default)

var SettingsManager.showLyricsOnPlayer: Boolean
    get() = getBoolean("showLyricsOnPlayer", false)
    set(value) = setBoolean("showLyricsOnPlayer", value)

fun SettingsManager.showLyricsOnPlayerFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("showLyricsOnPlayer", default)

var SettingsManager.swipeLyrics: Boolean
    get() = getBoolean("swipeLyrics", false)
    set(value) = setBoolean("swipeLyrics", value)

fun SettingsManager.swipeLyricsFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("swipeLyrics", default)

var SettingsManager.enableLyricsThumbnailPlayPause: Boolean
    get() = getBoolean("enableLyricsThumbnailPlayPause", false)
    set(value) = setBoolean("enableLyricsThumbnailPlayPause", value)

fun SettingsManager.enableLyricsThumbnailPlayPauseFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("enableLyricsThumbnailPlayPause", default)

var SettingsManager.lyricsTextPosition: String
    get() = getString("lyricsTextPosition", "")
    set(value) = setString("lyricsTextPosition", value)

fun SettingsManager.lyricsTextPositionFlow(default: String = ""): Flow<String> = getStringFlow("lyricsTextPosition", default)

var SettingsManager.lyricsClick: Boolean
    get() = getBoolean("lyricsClick", false)
    set(value) = setBoolean("lyricsClick", value)

fun SettingsManager.lyricsClickFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("lyricsClick", default)

var SettingsManager.lyricsScroll: Boolean
    get() = getBoolean("lyricsScrollKey", false)
    set(value) = setBoolean("lyricsScrollKey", value)

fun SettingsManager.lyricsScrollFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("lyricsScrollKey", default)

var SettingsManager.lyricsRomanizeJapanese: Boolean
    get() = getBoolean("lyricsRomanizeJapanese", false)
    set(value) = setBoolean("lyricsRomanizeJapanese", value)

fun SettingsManager.lyricsRomanizeJapaneseFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("lyricsRomanizeJapanese", default)

var SettingsManager.lyricsRomanizeKorean: Boolean
    get() = getBoolean("lyricsRomanizeKorean", false)
    set(value) = setBoolean("lyricsRomanizeKorean", value)

fun SettingsManager.lyricsRomanizeKoreanFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("lyricsRomanizeKorean", default)

var SettingsManager.lyricsRomanizeChinese: Boolean
    get() = getBoolean("lyricsRomanizeChinese", false)
    set(value) = setBoolean("lyricsRomanizeChinese", value)

fun SettingsManager.lyricsRomanizeChineseFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("lyricsRomanizeChinese", default)

var SettingsManager.lyricsRomanizeRussian: Boolean
    get() = getBoolean("lyricsRomanizeRussian", false)
    set(value) = setBoolean("lyricsRomanizeRussian", value)

fun SettingsManager.lyricsRomanizeRussianFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("lyricsRomanizeRussian", default)

var SettingsManager.lyricsRomanizeUkrainian: Boolean
    get() = getBoolean("lyricsRomanizeUkrainian", false)
    set(value) = setBoolean("lyricsRomanizeUkrainian", value)

fun SettingsManager.lyricsRomanizeUkrainianFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("lyricsRomanizeUkrainian", default)

var SettingsManager.lyricsRomanizeSerbian: Boolean
    get() = getBoolean("lyricsRomanizeSerbian", false)
    set(value) = setBoolean("lyricsRomanizeSerbian", value)

fun SettingsManager.lyricsRomanizeSerbianFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("lyricsRomanizeSerbian", default)

var SettingsManager.lyricsRomanizeBulgarian: Boolean
    get() = getBoolean("lyricsRomanizeBulgarian", false)
    set(value) = setBoolean("lyricsRomanizeBulgarian", value)

fun SettingsManager.lyricsRomanizeBulgarianFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("lyricsRomanizeBulgarian", default)

var SettingsManager.lyricsRomanizeBelarusian: Boolean
    get() = getBoolean("lyricsRomanizeBelarusian", false)
    set(value) = setBoolean("lyricsRomanizeBelarusian", value)

fun SettingsManager.lyricsRomanizeBelarusianFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("lyricsRomanizeBelarusian", default)

var SettingsManager.lyricsRomanizeKyrgyz: Boolean
    get() = getBoolean("lyricsRomanizeKyrgyz", false)
    set(value) = setBoolean("lyricsRomanizeKyrgyz", value)

fun SettingsManager.lyricsRomanizeKyrgyzFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("lyricsRomanizeKyrgyz", default)

var SettingsManager.lyricsRomanizeMacedonian: Boolean
    get() = getBoolean("lyricsRomanizeMacedonian", false)
    set(value) = setBoolean("lyricsRomanizeMacedonian", value)

fun SettingsManager.lyricsRomanizeMacedonianFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("lyricsRomanizeMacedonian", default)

var SettingsManager.lyricsRomanizeHindi: Boolean
    get() = getBoolean("lyricsRomanizeHindi", false)
    set(value) = setBoolean("lyricsRomanizeHindi", value)

fun SettingsManager.lyricsRomanizeHindiFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("lyricsRomanizeHindi", default)

var SettingsManager.lyricsRomanizePunjabi: Boolean
    get() = getBoolean("lyricsRomanizePunjabi", false)
    set(value) = setBoolean("lyricsRomanizePunjabi", value)

fun SettingsManager.lyricsRomanizePunjabiFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("lyricsRomanizePunjabi", default)

var SettingsManager.lyricsRomanizeAsMain: Boolean
    get() = getBoolean("lyricsRomanizeAsMain", false)
    set(value) = setBoolean("lyricsRomanizeAsMain", value)

fun SettingsManager.lyricsRomanizeAsMainFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("lyricsRomanizeAsMain", default)

var SettingsManager.lyricsRomanizeCyrillicByLine: Boolean
    get() = getBoolean("lyricsRomanizeCyrillicByLine", false)
    set(value) = setBoolean("lyricsRomanizeCyrillicByLine", value)

fun SettingsManager.lyricsRomanizeCyrillicByLineFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("lyricsRomanizeCyrillicByLine", default)

var SettingsManager.translateLyrics: Boolean
    get() = getBoolean("translateLyrics", false)
    set(value) = setBoolean("translateLyrics", value)

fun SettingsManager.translateLyricsFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("translateLyrics", default)

var SettingsManager.openRouterApi: String
    get() = getString("openRouterApiKey", "")
    set(value) = setString("openRouterApiKey", value)

fun SettingsManager.openRouterApiFlow(default: String = ""): Flow<String> = getStringFlow("openRouterApiKey", default)

var SettingsManager.aiProvider: String
    get() = getString("aiProvider", "")
    set(value) = setString("aiProvider", value)

fun SettingsManager.aiProviderFlow(default: String = ""): Flow<String> = getStringFlow("aiProvider", default)

var SettingsManager.openRouterBaseUrl: String
    get() = getString("openRouterBaseUrl", "")
    set(value) = setString("openRouterBaseUrl", value)

fun SettingsManager.openRouterBaseUrlFlow(default: String = ""): Flow<String> = getStringFlow("openRouterBaseUrl", default)

var SettingsManager.openRouterModel: String
    get() = getString("openRouterModel", "")
    set(value) = setString("openRouterModel", value)

fun SettingsManager.openRouterModelFlow(default: String = ""): Flow<String> = getStringFlow("openRouterModel", default)

var SettingsManager.translateMode: String
    get() = getString("translateMode", "")
    set(value) = setString("translateMode", value)

fun SettingsManager.translateModeFlow(default: String = ""): Flow<String> = getStringFlow("translateMode", default)

var SettingsManager.translateLanguage: String
    get() = getString("translateLanguage", "")
    set(value) = setString("translateLanguage", value)

fun SettingsManager.translateLanguageFlow(default: String = ""): Flow<String> = getStringFlow("translateLanguage", default)

var SettingsManager.autoTranslate: Boolean
    get() = getBoolean("autoTranslate", false)
    set(value) = setBoolean("autoTranslate", value)

fun SettingsManager.autoTranslateFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("autoTranslate", default)

var SettingsManager.aiRecommendations: Boolean
    get() = getBoolean("aiRecommendations", false)
    set(value) = setBoolean("aiRecommendations", value)

fun SettingsManager.aiRecommendationsFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("aiRecommendations", default)

var SettingsManager.deeplApi: String
    get() = getString("deeplApiKey", "")
    set(value) = setString("deeplApiKey", value)

fun SettingsManager.deeplApiFlow(default: String = ""): Flow<String> = getStringFlow("deeplApiKey", default)

var SettingsManager.deeplFormality: String
    get() = getString("deeplFormality", "")
    set(value) = setString("deeplFormality", value)

fun SettingsManager.deeplFormalityFlow(default: String = ""): Flow<String> = getStringFlow("deeplFormality", default)

var SettingsManager.lyricsGlowEffect: Boolean
    get() = getBoolean("lyricsGlowEffect", false)
    set(value) = setBoolean("lyricsGlowEffect", value)

fun SettingsManager.lyricsGlowEffectFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("lyricsGlowEffect", default)

var SettingsManager.appleMusicLyricsBlur: Boolean
    get() = getBoolean("appleMusicLyricsBlur", false)
    set(value) = setBoolean("appleMusicLyricsBlur", value)

fun SettingsManager.appleMusicLyricsBlurFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("appleMusicLyricsBlur", default)

var SettingsManager.lyricsStandardBlur: Boolean
    get() = getBoolean("lyricsStandardBlur", false)
    set(value) = setBoolean("lyricsStandardBlur", value)

fun SettingsManager.lyricsStandardBlurFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("lyricsStandardBlur", default)

var SettingsManager.hideStatusBarOnFullscreen: Boolean
    get() = getBoolean("hideStatusBarOnFullscreen", false)
    set(value) = setBoolean("hideStatusBarOnFullscreen", value)

fun SettingsManager.hideStatusBarOnFullscreenFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("hideStatusBarOnFullscreen", default)

var SettingsManager.lyricsAnimationStyle: String
    get() = getString("lyricsAnimationStyle", "")
    set(value) = setString("lyricsAnimationStyle", value)

fun SettingsManager.lyricsAnimationStyleFlow(default: String = ""): Flow<String> = getStringFlow("lyricsAnimationStyle", default)

var SettingsManager.lyricsTextSize: Float
    get() = getFloat("lyricsTextSize", 0f)
    set(value) = setFloat("lyricsTextSize", value)

fun SettingsManager.lyricsTextSizeFlow(default: Float = 0f): Flow<Float> = getFloatFlow("lyricsTextSize", default)

var SettingsManager.lyricsLineSpacing: Float
    get() = getFloat("lyricsLineSpacing", 0f)
    set(value) = setFloat("lyricsLineSpacing", value)

fun SettingsManager.lyricsLineSpacingFlow(default: Float = 0f): Flow<Float> = getFloatFlow("lyricsLineSpacing", default)

var SettingsManager.playerVolume: Float
    get() = getFloat("playerVolume", 0f)
    set(value) = setFloat("playerVolume", value)

fun SettingsManager.playerVolumeFlow(default: Float = 0f): Flow<Float> = getFloatFlow("playerVolume", default)

var SettingsManager.repeatMode: Int
    get() = getInt("repeatMode", 0)
    set(value) = setInt("repeatMode", value)

fun SettingsManager.repeatModeFlow(default: Int = 0): Flow<Int> = getIntFlow("repeatMode", default)

var SettingsManager.searchSource: String
    get() = getString("searchSource", "")
    set(value) = setString("searchSource", value)

fun SettingsManager.searchSourceFlow(default: String = ""): Flow<String> = getStringFlow("searchSource", default)

var SettingsManager.swipeThumbnail: Boolean
    get() = getBoolean("swipeThumbnail", false)
    set(value) = setBoolean("swipeThumbnail", value)

fun SettingsManager.swipeThumbnailFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("swipeThumbnail", default)

var SettingsManager.rotatingThumbnail: Boolean
    get() = getBoolean("rotatingThumbnail", false)
    set(value) = setBoolean("rotatingThumbnail", value)

fun SettingsManager.rotatingThumbnailFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("rotatingThumbnail", default)

var SettingsManager.canvasThumbnailAnimation: Boolean
    get() = getBoolean("canvasThumbnailAnimation", false)
    set(value) = setBoolean("canvasThumbnailAnimation", value)

fun SettingsManager.canvasThumbnailAnimationFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("canvasThumbnailAnimation", default)

var SettingsManager.swipeSensitivity: Float
    get() = getFloat("swipeSensitivity", 0f)
    set(value) = setFloat("swipeSensitivity", value)

fun SettingsManager.swipeSensitivityFlow(default: Float = 0f): Flow<Float> = getFloatFlow("swipeSensitivity", default)

var SettingsManager.visitorData: String
    get() = getString("visitorData", "")
    set(value) = setString("visitorData", value)

fun SettingsManager.visitorDataFlow(default: String = ""): Flow<String> = getStringFlow("visitorData", default)

var SettingsManager.dataSyncId: String
    get() = getString("dataSyncId", "")
    set(value) = setString("dataSyncId", value)

fun SettingsManager.dataSyncIdFlow(default: String = ""): Flow<String> = getStringFlow("dataSyncId", default)

var SettingsManager.innerTubeCookie: String
    get() = getString("innerTubeCookie", "")
    set(value) = setString("innerTubeCookie", value)

fun SettingsManager.innerTubeCookieFlow(default: String = ""): Flow<String> = getStringFlow("innerTubeCookie", default)

var SettingsManager.accountName: String
    get() = getString("accountName", "")
    set(value) = setString("accountName", value)

fun SettingsManager.accountNameFlow(default: String = ""): Flow<String> = getStringFlow("accountName", default)

var SettingsManager.accountEmail: String
    get() = getString("accountEmail", "")
    set(value) = setString("accountEmail", value)

fun SettingsManager.accountEmailFlow(default: String = ""): Flow<String> = getStringFlow("accountEmail", default)

var SettingsManager.accountChannelHandle: String
    get() = getString("accountChannelHandle", "")
    set(value) = setString("accountChannelHandle", value)

fun SettingsManager.accountChannelHandleFlow(default: String = ""): Flow<String> = getStringFlow("accountChannelHandle", default)

var SettingsManager.useLoginForBrowse: Boolean
    get() = getBoolean("useLoginForBrowse", false)
    set(value) = setBoolean("useLoginForBrowse", value)

fun SettingsManager.useLoginForBrowseFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("useLoginForBrowse", default)

var SettingsManager.lastOpenedVersionCode: Int
    get() = getInt("lastOpenedVersionCode", 0)
    set(value) = setInt("lastOpenedVersionCode", value)

fun SettingsManager.lastOpenedVersionCodeFlow(default: Int = 0): Flow<Int> = getIntFlow("lastOpenedVersionCode", default)

var SettingsManager.spatialAudioEnabled: Boolean
    get() = getBoolean("spatial_audio_enabled", false)
    set(value) = setBoolean("spatial_audio_enabled", value)

fun SettingsManager.spatialAudioEnabledFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("spatial_audio_enabled", default)

var SettingsManager.spatialAudioStrength: Float
    get() = getFloat("spatial_audio_strength", 0f)
    set(value) = setFloat("spatial_audio_strength", value)

fun SettingsManager.spatialAudioStrengthFlow(default: Float = 0f): Flow<Float> = getFloatFlow("spatial_audio_strength", default)

var SettingsManager.crossfeedEnabled: Boolean
    get() = getBoolean("crossfeed_enabled", false)
    set(value) = setBoolean("crossfeed_enabled", value)

fun SettingsManager.crossfeedEnabledFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("crossfeed_enabled", default)

var SettingsManager.bassBoost: Float
    get() = getFloat("bass_boost", 0f)
    set(value) = setFloat("bass_boost", value)

fun SettingsManager.bassBoostFlow(default: Float = 0f): Flow<Float> = getFloatFlow("bass_boost", default)

var SettingsManager.virtualizer: Float
    get() = getFloat("virtualizer", 0f)
    set(value) = setFloat("virtualizer", value)

fun SettingsManager.virtualizerFlow(default: Float = 0f): Flow<Float> = getFloatFlow("virtualizer", default)

var SettingsManager.listenBrainzEnabled: Boolean
    get() = getBoolean("listenbrainz_enabled", false)
    set(value) = setBoolean("listenbrainz_enabled", value)

fun SettingsManager.listenBrainzEnabledFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("listenbrainz_enabled", default)

var SettingsManager.listenBrainzToken: String
    get() = getString("listenbrainz_token", "")
    set(value) = setString("listenbrainz_token", value)

fun SettingsManager.listenBrainzTokenFlow(default: String = ""): Flow<String> = getStringFlow("listenbrainz_token", default)

var SettingsManager.lrcLibLyricsEnabled: Boolean
    get() = getBoolean("lrclib_lyrics_enabled", false)
    set(value) = setBoolean("lrclib_lyrics_enabled", value)

fun SettingsManager.lrcLibLyricsEnabledFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("lrclib_lyrics_enabled", default)

var SettingsManager.kuGouLyricsEnabled: Boolean
    get() = getBoolean("kugou_lyrics_enabled", false)
    set(value) = setBoolean("kugou_lyrics_enabled", value)

fun SettingsManager.kuGouLyricsEnabledFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("kugou_lyrics_enabled", default)

var SettingsManager.unisonLyricsEnabled: Boolean
    get() = getBoolean("unison_lyrics_enabled", false)
    set(value) = setBoolean("unison_lyrics_enabled", value)

fun SettingsManager.unisonLyricsEnabledFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("unison_lyrics_enabled", default)

var SettingsManager.youTubeSubtitleLyricsEnabled: Boolean
    get() = getBoolean("youtube_subtitle_lyrics_enabled", false)
    set(value) = setBoolean("youtube_subtitle_lyrics_enabled", value)

fun SettingsManager.youTubeSubtitleLyricsEnabledFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("youtube_subtitle_lyrics_enabled", default)

var SettingsManager.preloadNextSongEnabled: Boolean
    get() = getBoolean("preload_next_song_enabled", false)
    set(value) = setBoolean("preload_next_song_enabled", value)

fun SettingsManager.preloadNextSongEnabledFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("preload_next_song_enabled", default)

var SettingsManager.preloadNextSongLimit: Int
    get() = getInt("preload_next_song_limit", 0)
    set(value) = setInt("preload_next_song_limit", value)

fun SettingsManager.preloadNextSongLimitFlow(default: Int = 0): Flow<Int> = getIntFlow("preload_next_song_limit", default)

var SettingsManager.preloadLyricsEnabled: Boolean
    get() = getBoolean("preload_lyrics_enabled", false)
    set(value) = setBoolean("preload_lyrics_enabled", value)

fun SettingsManager.preloadLyricsEnabledFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("preload_lyrics_enabled", default)

var SettingsManager.useFloatingNavBar: Boolean
    get() = getBoolean("useFloatingNavBar", false)
    set(value) = setBoolean("useFloatingNavBar", value)

fun SettingsManager.useFloatingNavBarFlow(default: Boolean = false): Flow<Boolean> = getBooleanFlow("useFloatingNavBar", default)

var SettingsManager.savedAccounts: String
    get() = getString("savedAccounts", "")
    set(value) = setString("savedAccounts", value)

fun SettingsManager.savedAccountsFlow(default: String = ""): Flow<String> = getStringFlow("savedAccounts", default)

var SettingsManager.liveBlurDensity: Float
    get() = getFloat("live_blur_density", 0f)
    set(value) = setFloat("live_blur_density", value)

fun SettingsManager.liveBlurDensityFlow(default: Float = 0f): Flow<Float> = getFloatFlow("live_blur_density", default)
